# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'submit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
Student=sqlite3.connect('students.db')
cursor=Student.cursor()
qu="SELECT * FROM records"

class Ui_Form(object):
    def insertQuery(self):
        cursor.execute(qu)
        records=cursor.fetchall()
        enr=self.enrl.text()
        na=self.name.text()
        mark=int(self.marks.text())
        exam=str(self.comboBox.currentText())
        print("Exam Type: ",exam)
        temp=0
        for record in records:
            if enr==record[0]:
                temp=1
                if exam=="T1":
                    cursor.execute("UPDATE student SET T1='"+str(mark)+"' WHERE enrl='"+enr+"';")
                    print("Database Updated")
                elif exam=="T2":
                    cursor.execute("UPDATE student SET T2='"+str(mark)+"' WHERE enrl='"+enr+"';")
                    print("Database Updated")
                elif exam=="T3":
                    cursor.execute("UPDATE student SET T3='"+str(mark)+"' WHERE enrl='"+enr+"';")
                    print("Database Updated")
                elif exam=="TA":
                    cursor.execute("UPDATE student SET TA='"+str(mark)+"' WHERE enrl='"+enr+"';")
                    print("Database Updated")
        if temp==0:
            print("Entering Records")
            print(exam=='T1')
            if exam=='T1':
                cursor.execute("INSERT INTO records (enrol, name, T1, T2, T3, TA) VALUES (?,?,?,?,?,?);",(enr,na,mark,'','',''))
                print("Entering marks in T1")
            elif exam=='T2':
                cursor.execute("INSERT INTO records (enrol, name, T1, T2, T3, TA) VALUES (?,?,?,?,?,?);",(enr,na,'',mark,'',''))
                print("Entering marks in T2")
            elif exam=='T3':
                cursor.execute("INSERT INTO records (enrol, name, T1, T2, T3, TA) VALUES (?,?,?,?,?,?);",(enr,na,'','',mark,''))
                print("Entering marks in T3")
            elif exam=='T4':
                cursor.execute("INSERT INTO records (enrol, name, T1, T2, T3, TA) VALUES (?,?,?,?,?,?);",(enr,na,'','','',mark))
                print("Entering marks in TA")
        Student.commit()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(468, 463)
        self.submitButton = QtWidgets.QPushButton(Form)
        self.submitButton.setGeometry(QtCore.QRect(170, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 310, 291, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.marks = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.marks.setObjectName("marks")
        self.horizontalLayout_2.addWidget(self.marks)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 70, 351, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.enrl = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.enrl.setObjectName("enrl")
        self.horizontalLayout_3.addWidget(self.enrl)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(110, 150, 291, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.name = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.name.setObjectName("name")
        self.horizontalLayout_4.addWidget(self.name)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 230, 51, 78))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(170, 260, 231, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, -1, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        
        self.submitButton.clicked.connect(self.insertQuery)

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.marks.clear)
        self.pushButton_2.clicked.connect(self.name.clear)
        self.pushButton_2.clicked.connect(self.enrl.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.submitButton.setText(_translate("Form", "SUBMIT"))
        self.pushButton_2.setText(_translate("Form", "RESET"))
        self.label_4.setText(_translate("Form", "Marks"))
        self.label.setText(_translate("Form", "Enrollment No."))
        self.label_2.setText(_translate("Form", "Name:"))
        self.label_3.setText(_translate("Form", "Exam"))
        self.comboBox.setItemText(0, _translate("Form", "T1"))
        self.comboBox.setItemText(1, _translate("Form", "T2"))
        self.comboBox.setItemText(2, _translate("Form", "T3"))
        self.comboBox.setItemText(3, _translate("Form", "TA"))
        self.label_5.setText(_translate("Form", "ENTER DETAILS"))

def show():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
